site_name: Booby documentation
site_url: http://booby.monomelodies.nl/
repo_url: https://github.com/monomelodies/booby

pages:
- Home:
    - 'Quickstart': 'index.md'

copyright: Copyright &copy; 2015, <a href="http://monomelodies.nl/">Marijn Ophorst</a>

